/**
 * Type declarations for every exported subpath.
 *
 * Generated from the same sources as the modules themselves: the icon list, the component
 * manifest and the palette data. Nothing here restates a shape by hand, because a
 * hand-written .d.ts is a second description of the same thing that drifts silently the
 * first time the first description changes.
 *
 * The naming helpers come from the react generator rather than being reimplemented, so the
 * declared export names cannot disagree with the emitted ones.
 *
 * The target that drove the shapes: get("combo").props and get("combo").a11y.keys should
 * both autocomplete in an editor, which needs a literal union of component keys and an
 * overload that resolves a known key to a defined component.
 */
import { icons, categories as iconCategories } from '../../kapehan-icons.js';
import { components, COMPONENT_CATEGORIES } from '../components.mjs';
import { componentName, componentAlias, iconName } from './react.mjs';
import { doodles } from './doodles.mjs';

export const name = 'types';

export const pkg = {
  // A types condition must come first in each exports entry, so TypeScript sees it before
  // the runtime target. That ordering is asserted in check() rather than trusted.
  //
  // ./palettes.json is deliberately absent. TypeScript will not take a sidecar declaration
  // as the default export of a .json specifier: pointing types at one makes
  // `palettes[0].accent` fail with "Property '0' does not exist", where with no types
  // condition at all resolveJsonModule reads the real file and types it exactly. Measured
  // both ways with tsc 5.6 before removing it.
  types: {
    './kapehan-icons.js': './kapehan-icons.d.ts',
    './kapehan-components.js': './kapehan-components.d.ts',
    './kape-icon.js': './kape-icon.d.ts',
    './kape-doodle.js': './kape-doodle.d.ts',
    './react': './react/index.d.ts',
    './react/index.js': './react/index.d.ts',
    './react/icons.js': './react/icons.d.ts',
    './react/components.js': './react/components.d.ts',
  },
  files: ['kapehan-icons.d.ts', 'kapehan-components.d.ts', 'kape-icon.d.ts', 'kape-doodle.d.ts'],
};

const HEAD = (what) => `/**
 * ${what}
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run \`npm run build\`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */
`;

/** A quoted union, wrapped so a 42-name list stays readable. */
const union = (values, indent = '  ') => {
  const out = [];
  let line = '';
  for (const v of values) {
    const piece = `| ${JSON.stringify(v)} `;
    if (line.length + piece.length > 92) { out.push(line.trimEnd()); line = ''; }
    line += piece;
  }
  if (line.trim()) out.push(line.trimEnd());
  return out.map((l) => indent + l).join('\n');
};

function iconsDts() {
  const names = icons.map((i) => i.name);
  const aliases = [...new Set(icons.flatMap((i) => i.aliases))];
  return (
    HEAD(`The ${icons.length} icons, the shared palette and the helpers that build an SVG.`) +
    `
/** Every icon's own name. */
export type IconName =
${union(names)};

/** The alternative names lookup accepts. */
export type IconAlias =
${union(aliases)};

/** Anything <kape-icon name> resolves. */
export type IconLookup = IconName | IconAlias;

export type IconCategory =
${union(iconCategories)};

export interface Icon {
  name: IconName;
  aliases: IconAlias[];
  tags: string[];
  category: IconCategory;
  /** The inner SVG markup, without the <svg> wrapper. */
  body: string;
  /** A hand-tuned one-colour body, when the automatic conversion is not good enough. */
  monoBody?: string;
}

/** The shared drawing palette, keyed by role. */
export declare const palette: Record<string, string>;

export declare const icons: Icon[];
export declare const categories: IconCategory[];

/** Rewrite a body to currentColor. */
export declare function toMono(body: string): string;

/** Drop the data-mono hints, which are build-time only. */
export declare function stripHints(body: string): string;

/** The one-colour body for an icon: its own if it has one, otherwise converted. */
export declare function monoOf(icon: Icon): string;

/** Wrap a body in a sized <svg>. */
export declare function wrap(name: string, body: string, size?: number): string;
`
  );
}

function componentsDts(comps) {
  const keys = comps.map((c) => c.key);
  return (
    HEAD(`The ${comps.length} components: props, the accessibility contract and the markup.`) +
    `
/** Every component key. Also what get() accepts. */
export type ComponentKey =
${union(keys)};

export type ComponentCategory =
${union(COMPONENT_CATEGORIES)};

/** One row of a component's props table. */
export interface ComponentProp {
  name: string;
  /** The type as written for a reader, e.g. "Array<{ id: string }>". */
  type: string;
  /** The default as written, or "—" when there is none. */
  default: string;
  required: boolean;
  description: string;
}

/** What a component must do to be accessible. Not enforced, documented. */
export interface ComponentA11y {
  /** ARIA roles the markup sets. */
  roles: string[];
  /** ARIA attributes the markup sets. */
  attrs: string[];
  /** Keys the component handles. */
  keys: string[];
}

export interface Component {
  key: ComponentKey;
  label: string;
  cat: ComponentCategory;
  props: ComponentProp[];
  a11y: ComponentA11y;
  /** Plain HTML markup. */
  html: string;
  /** The same component as JSX. */
  react: string;
  /** The component's own CSS, from kapehan.css. */
  css: string;
}

export declare const categories: ComponentCategory[];
export declare const components: Component[];

/**
 * Look a component up by key.
 *
 * A known key resolves to a Component, so get("combo").props needs no non-null assertion.
 * Any other string may miss, and says so.
 */
export declare function get<K extends ComponentKey>(key: K): Component;
export declare function get(key: string): Component | undefined;

/** Components in one group, in canvas order. */
export declare function byCategory(cat: ComponentCategory): Component[];
`
  );
}

function kapeIconDts() {
  return (
    HEAD('The <kape-icon> custom element.') +
    `
import type { Icon, IconLookup } from './kapehan-icons.js';

export declare const ICONS: Icon[];

/**
 * Renders one icon. Registered as <kape-icon> on import, in a browser.
 *
 * Importing this on a server is safe: it only defines the element when customElements
 * exists, so a framework that evaluates imports during SSR will not throw.
 */
export declare class KapeIcon extends HTMLElement {
  /** Which icon to draw. */
  name: IconLookup;
  /** Pixel size of the square viewport. Defaults to 48. */
  size: number;
  /** Draw in one colour, inheriting currentColor. */
  mono: boolean;
}

declare global {
  interface HTMLElementTagNameMap {
    'kape-icon': KapeIcon;
  }
}

export {};
`
  );
}

function kapeDoodleDts(doodleNames) {
  return (
    HEAD(`The <kape-doodle> custom element and its ${doodleNames.length} drawings.`) +
    `
export type DoodleName =
${union(doodleNames)};

export interface Doodle {
  name: DoodleName;
  label: string;
  /** An accessible description of the scene. */
  aria: string;
  /** The viewBox as written, e.g. "0 0 640 400". */
  viewBox: string;
  /** Scenes are 640x400, states are 400x400. */
  width: number;
  height: number;
  /** The inner SVG markup, without the <svg> wrapper. */
  body: string;
}

export declare const DOODLES: Doodle[];

/** Renders one doodle. Registered as <kape-doodle> on import, in a browser. */
export declare class KapeDoodle extends HTMLElement {
  name: DoodleName;
  /** Hold the drawing still instead of animating it. */
  still: boolean;
}

declare global {
  interface HTMLElementTagNameMap {
    'kape-doodle': KapeDoodle;
  }
}

export {};
`
  );
}

/** The React halves. Props are the same for every icon, so one interface covers all 42. */
function reactIconsDts() {
  const lines = icons.map((i) => `export declare const ${iconName(i)}: KapeIconComponent;`);
  return (
    HEAD(`The ${icons.length} icons as React components.`) +
    `
import type { SVGProps } from 'react';
import type { IconLookup } from '../kapehan-icons.js';

export interface KapeIconProps extends Omit<SVGProps<SVGSVGElement>, 'name'> {
  /** Pixel size of the square viewport. Defaults to 24. */
  size?: number;
  /** Draw in one colour, inheriting currentColor. */
  mono?: boolean;
  /** Accepted and ignored; recolour with CSS instead. */
  colour?: string;
  /** An accessible name. Without it the icon is aria-hidden. */
  label?: string;
}

export type KapeIconComponent = (props: KapeIconProps) => JSX.Element;

/** Render any icon by name. */
export declare function KapeIcon(props: KapeIconProps & { name: IconLookup }): JSX.Element;

${lines.join('\n')}
`
  );
}

function reactComponentsDts(comps) {
  const decls = [];
  for (const c of comps) {
    const n = componentName(c);
    decls.push(`/** ${c.label}. ${c.cat}. */
export declare function ${n}(props: KapeComponentProps): JSX.Element;`);
    const alias = componentAlias(c);
    if (alias) decls.push(`export { ${n} as ${alias} };`);
  }
  return (
    HEAD(`The ${comps.length} components as React components.`) +
    `
import type { HTMLAttributes } from 'react';

/**
 * Every component takes its own props plus whatever is left over, which lands on the root
 * element. The per-component prop tables live in the manifest, where they are data:
 *
 *   import { get } from 'kapehan/kapehan-components.js';
 *   get('combo').props
 */
export interface KapeComponentProps extends HTMLAttributes<HTMLElement> {
  [prop: string]: unknown;
}

${decls.join('\n\n')}
`
  );
}

function reactIndexDts() {
  return (
    HEAD('Every Kapehan React export.') +
    `
export * from './icons.js';
export * from './components.js';
`
  );
}

export async function artifacts() {
  const [comps, dood] = await Promise.all([components(), doodles()]);
  return new Map([
    ['kapehan-icons.d.ts', iconsDts()],
    ['kapehan-components.d.ts', componentsDts(comps)],
    ['kape-icon.d.ts', kapeIconDts()],
    ['kape-doodle.d.ts', kapeDoodleDts(dood.map((d) => d.name))],
    ['react/icons.d.ts', reactIconsDts()],
    ['react/components.d.ts', reactComponentsDts(comps)],
    ['react/index.d.ts', reactIndexDts()],
  ]);
}

export async function check({ root, expected }) {
  const fail = [];
  const { readFile } = await import('node:fs/promises');
  const { join } = await import('node:path');
  const pkgJson = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));

  for (const [sub, dts] of Object.entries(pkg.types)) {
    const entry = pkgJson.exports?.[sub];
    if (entry === undefined) {
      fail.push(`package.json exports has no ${sub}, so its types cannot be declared`);
      continue;
    }
    if (typeof entry === 'string') {
      fail.push(`package.json exports ${sub} as a bare path, so TypeScript gets no types; use { types, default }`);
      continue;
    }
    if (entry.types !== dts) {
      fail.push(`package.json exports ${sub} should declare types ${dts}, has ${entry.types ?? 'nothing'}`);
    }
    // Condition order is load-bearing: the first match wins, so a types condition after
    // default is never consulted and the package silently ships untyped.
    const first = Object.keys(entry)[0];
    if (first !== 'types') {
      fail.push(`package.json exports ${sub} lists "${first}" before "types"; types must come first or it is ignored`);
    }
  }

  // Every declaration the generator writes must be in files[], or the tarball omits it and
  // the exports entry points at nothing.
  for (const path of expected.keys()) {
    if (!path.endsWith('.d.ts')) continue;
    const top = path.split('/')[0];
    if (!(pkgJson.files ?? []).includes(top)) {
      fail.push(`package.json files does not ship ${top}, so ${path} would not be published`);
    }
  }

  // A declaration that names an export the module does not have is worse than none: the
  // editor autocompletes it and the import fails at runtime.
  const pairs = [
    ['react/icons.d.ts', 'react/icons.js'],
    ['react/components.d.ts', 'react/components.js'],
  ];
  for (const [dts, js] of pairs) {
    const d = expected.get(dts) ?? '';
    const j = expected.get(js) ?? '';
    const declared = new Set([...d.matchAll(/export declare (?:const|function) (\w+)/g)].map((m) => m[1]));
    for (const m of d.matchAll(/export \{ \w+ as (\w+) \}/g)) declared.add(m[1]);
    const real = new Set([...j.matchAll(/export (?:const|function) (\w+)/g)].map((m) => m[1]));
    for (const m of j.matchAll(/export \{ \w+ as (\w+) \}/g)) real.add(m[1]);
    for (const n of declared) if (!real.has(n)) fail.push(`${dts} declares ${n}, which ${js} does not export`);
    for (const n of real) if (!declared.has(n)) fail.push(`${js} exports ${n}, which ${dts} does not declare`);
  }

  return fail;
}
