/**
 * The <kape-doodle> custom element and its 24 drawings.
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run `npm run build`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */

export type DoodleName =
  | "pour-over" | "barista" | "latte-sip" | "coffee-donut" | "friends" | "laptop" | "cashier"
  | "reading-alone" | "latte-art" | "closing-up" | "beans-roasting" | "cup-pandesal"
  | "loading" | "not-found" | "empty" | "error" | "success" | "offline" | "no-results"
  | "empty-cart" | "email-sent" | "maintenance" | "sign-in" | "notifications";

export interface Doodle {
  name: DoodleName;
  label: string;
  /** An accessible description of the scene. */
  aria: string;
  /** The viewBox as written, e.g. "0 0 640 400". */
  viewBox: string;
  /** Scenes are 640x400, states are 400x400. */
  width: number;
  height: number;
  /** The inner SVG markup, without the <svg> wrapper. */
  body: string;
}

export declare const DOODLES: Doodle[];

/** Renders one doodle. Registered as <kape-doodle> on import, in a browser. */
export declare class KapeDoodle extends HTMLElement {
  name: DoodleName;
  /** Hold the drawing still instead of animating it. */
  still: boolean;
}

declare global {
  interface HTMLElementTagNameMap {
    'kape-doodle': KapeDoodle;
  }
}

export {};
