/**
 * The 42 icons, the shared palette and the helpers that build an SVG.
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run `npm run build`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */

/** Every icon's own name. */
export type IconName =
  | "espresso" | "americano" | "latte" | "macchiato" | "cappuccino" | "mocha" | "barako"
  | "cold-brew" | "tablea" | "coffee-cup" | "coffee-bean" | "coffee-sack" | "drip-bag"
  | "stamp-card" | "french-press" | "pour-over" | "moka-pot" | "aeropress" | "barako-pot"
  | "kettle" | "grinder" | "espresso-machine" | "tea" | "matcha" | "salabat"
  | "hot-chocolate" | "milk-tea" | "ube-latte" | "mango-shake" | "buko-juice" | "calamansi"
  | "halo-halo" | "sago-gulaman" | "buko-pandan" | "watermelon-shake" | "avocado-shake"
  | "pineapple-juice" | "donut" | "cake-slice" | "croissant" | "pandesal" | "ensaymada";

/** The alternative names lookup accepts. */
export type IconAlias =
  | "shot" | "cup-sm" | "long-black" | "cup-black" | "glass-latte" | "cup-tall"
  | "cup-marked" | "piccolo" | "cup-foam" | "capp" | "cup-choco" | "mochaccino"
  | "kapeng-barako" | "cup-barako" | "iced" | "cup-cold" | "tsokolate" | "cacao-tablet"
  | "takeaway" | "cup-togo" | "bean" | "sack" | "beans-bag" | "sachet" | "drip-sachet"
  | "loyalty" | "punch-card" | "press" | "plunger" | "v60" | "dripper" | "moka" | "stovetop"
  | "press-air" | "palayok" | "clay-pot" | "gooseneck" | "tea-kettle" | "mill" | "gilingan"
  | "machine" | "barista-bar" | "hot-tea" | "tsaa" | "green-tea-latte" | "usucha"
  | "ginger-tea" | "ginger" | "cocoa" | "tsokolate-drink" | "boba" | "pearl-tea" | "ube"
  | "purple-yam" | "shake" | "smoothie" | "coconut" | "buko" | "citrus" | "juice"
  | "halohalo" | "shaved-ice" | "samalamig" | "gulaman" | "pandan" | "coconut-pandan"
  | "pakwan" | "melon-shake" | "avocado" | "green-shake" | "pinya" | "pineapple" | "doughnut"
  | "ring" | "cake" | "slice" | "pastry" | "crescent" | "bun" | "bread-roll" | "brioche"
  | "cheese-bun";

/** Anything <kape-icon name> resolves. */
export type IconLookup = IconName | IconAlias;

export type IconCategory =
  | "Drinks" | "Tea & more" | "Tropical" | "Desserts" | "Vessels" | "Beans" | "Brewers"
  | "Equipment";

export interface Icon {
  name: IconName;
  aliases: IconAlias[];
  tags: string[];
  category: IconCategory;
  /** The inner SVG markup, without the <svg> wrapper. */
  body: string;
  /** A hand-tuned one-colour body, when the automatic conversion is not good enough. */
  monoBody?: string;
}

/** The shared drawing palette, keyed by role. */
export declare const palette: Record<string, string>;

export declare const icons: Icon[];
export declare const categories: IconCategory[];

/** Rewrite a body to currentColor. */
export declare function toMono(body: string): string;

/** Drop the data-mono hints, which are build-time only. */
export declare function stripHints(body: string): string;

/** The one-colour body for an icon: its own if it has one, otherwise converted. */
export declare function monoOf(icon: Icon): string;

/** Wrap a body in a sized <svg>. */
export declare function wrap(name: string, body: string, size?: number): string;
