/**
 * The 30 components: props, the accessibility contract and the markup.
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run `npm run build`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */

/** Every component key. Also what get() accepts. */
export type ComponentKey =
  | "button" | "chip" | "input" | "seg" | "toast" | "stamps" | "row" | "stepper" | "switch"
  | "check" | "select" | "tabs" | "card" | "tag" | "avatar" | "dialog" | "tip" | "skeleton"
  | "progress" | "pager" | "acc" | "table" | "crumbs" | "upload" | "edit" | "combo" | "multi"
  | "range" | "cmdk" | "drawer";

export type ComponentCategory =
  | "Actions" | "Forms" | "Data" | "Feedback" | "Navigation" | "Overlays";

/** One row of a component's props table. */
export interface ComponentProp {
  name: string;
  /** The type as written for a reader, e.g. "Array<{ id: string }>". */
  type: string;
  /** The default as written, or "—" when there is none. */
  default: string;
  required: boolean;
  description: string;
}

/** What a component must do to be accessible. Not enforced, documented. */
export interface ComponentA11y {
  /** ARIA roles the markup sets. */
  roles: string[];
  /** ARIA attributes the markup sets. */
  attrs: string[];
  /** Keys the component handles. */
  keys: string[];
}

export interface Component {
  key: ComponentKey;
  label: string;
  cat: ComponentCategory;
  props: ComponentProp[];
  a11y: ComponentA11y;
  /** Plain HTML markup. */
  html: string;
  /** The same component as JSX. */
  react: string;
  /** The component's own CSS, from kapehan.css. */
  css: string;
}

export declare const categories: ComponentCategory[];
export declare const components: Component[];

/**
 * Look a component up by key.
 *
 * A known key resolves to a Component, so get("combo").props needs no non-null assertion.
 * Any other string may miss, and says so.
 */
export declare function get<K extends ComponentKey>(key: K): Component;
export declare function get(key: string): Component | undefined;

/** Components in one group, in canvas order. */
export declare function byCategory(cat: ComponentCategory): Component[];
