/**
 * The <kape-icon> custom element.
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run `npm run build`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */

import type { Icon, IconLookup } from './kapehan-icons.js';

export declare const ICONS: Icon[];

/**
 * Renders one icon. Registered as <kape-icon> on import, in a browser.
 *
 * Importing this on a server is safe: it only defines the element when customElements
 * exists, so a framework that evaluates imports during SSR will not throw.
 */
export declare class KapeIcon extends HTMLElement {
  /** Which icon to draw. */
  name: IconLookup;
  /** Pixel size of the square viewport. Defaults to 48. */
  size: number;
  /** Draw in one colour, inheriting currentColor. */
  mono: boolean;
}

declare global {
  interface HTMLElementTagNameMap {
    'kape-icon': KapeIcon;
  }
}

export {};
