/**
 * The 30 components as React components.
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run `npm run build`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */

import type { HTMLAttributes } from 'react';

/**
 * Every component takes its own props plus whatever is left over, which lands on the root
 * element. The per-component prop tables live in the manifest, where they are data:
 *
 *   import { get } from 'kapehan/kapehan-components.js';
 *   get('combo').props
 */
export interface KapeComponentProps extends HTMLAttributes<HTMLElement> {
  [prop: string]: unknown;
}

/** Button. Actions. */
export declare function KapeButton(props: KapeComponentProps): JSX.Element;

/** Chips. Actions. */
export declare function KapeChip(props: KapeComponentProps): JSX.Element;

export { KapeChip as KapeChips };

/** Input. Forms. */
export declare function KapeInput(props: KapeComponentProps): JSX.Element;

/** Segmented. Actions. */
export declare function KapeSeg(props: KapeComponentProps): JSX.Element;

export { KapeSeg as KapeSegmented };

/** Toast. Feedback. */
export declare function KapeToast(props: KapeComponentProps): JSX.Element;

/** Stamp card. Feedback. */
export declare function KapeStamps(props: KapeComponentProps): JSX.Element;

export { KapeStamps as KapeStampCard };

/** Menu row. Data. */
export declare function KapeRow(props: KapeComponentProps): JSX.Element;

export { KapeRow as KapeMenuRow };

/** Stepper. Forms. */
export declare function KapeStepper(props: KapeComponentProps): JSX.Element;

/** Switch. Actions. */
export declare function KapeSwitch(props: KapeComponentProps): JSX.Element;

/** Checkbox · Radio. Forms. */
export declare function KapeCheck(props: KapeComponentProps): JSX.Element;

export { KapeCheck as KapeCheckboxRadio };

/** Select. Forms. */
export declare function KapeSelect(props: KapeComponentProps): JSX.Element;

/** Tabs. Navigation. */
export declare function KapeTabs(props: KapeComponentProps): JSX.Element;

/** Card. Data. */
export declare function KapeCard(props: KapeComponentProps): JSX.Element;

/** Badge. Data. */
export declare function KapeTag(props: KapeComponentProps): JSX.Element;

export { KapeTag as KapeBadge };

/** Avatar. Navigation. */
export declare function KapeAvatar(props: KapeComponentProps): JSX.Element;

/** Dialog. Feedback. */
export declare function KapeDialog(props: KapeComponentProps): JSX.Element;

/** Tooltip. Navigation. */
export declare function KapeTip(props: KapeComponentProps): JSX.Element;

export { KapeTip as KapeTooltip };

/** Skeleton. Data. */
export declare function KapeSkeleton(props: KapeComponentProps): JSX.Element;

/** Progress. Feedback. */
export declare function KapeProgress(props: KapeComponentProps): JSX.Element;

/** Pagination. Navigation. */
export declare function KapePager(props: KapeComponentProps): JSX.Element;

export { KapePager as KapePagination };

/** Accordion. Data. */
export declare function KapeAcc(props: KapeComponentProps): JSX.Element;

export { KapeAcc as KapeAccordion };

/** Table. Data. */
export declare function KapeTable(props: KapeComponentProps): JSX.Element;

/** Breadcrumb. Navigation. */
export declare function KapeCrumbs(props: KapeComponentProps): JSX.Element;

export { KapeCrumbs as KapeBreadcrumb };

/** File upload. Forms. */
export declare function KapeUpload(props: KapeComponentProps): JSX.Element;

export { KapeUpload as KapeFileUpload };

/** Editable table. Data. */
export declare function KapeEdit(props: KapeComponentProps): JSX.Element;

export { KapeEdit as KapeEditableTable };

/** Combobox. Forms. */
export declare function KapeCombo(props: KapeComponentProps): JSX.Element;

export { KapeCombo as KapeCombobox };

/** Multi-select. Forms. */
export declare function KapeMulti(props: KapeComponentProps): JSX.Element;

export { KapeMulti as KapeMultiSelect };

/** Date range. Forms. */
export declare function KapeRange(props: KapeComponentProps): JSX.Element;

export { KapeRange as KapeDateRange };

/** Command palette. Overlays. */
export declare function KapeCmdk(props: KapeComponentProps): JSX.Element;

export { KapeCmdk as KapeCommandPalette };

/** Drawer. Overlays. */
export declare function KapeDrawer(props: KapeComponentProps): JSX.Element;
