/**
 * The 42 icons as React components.
 *
 * GENERATED by scripts/generators/types.mjs. Do not edit by hand; edit the source it reads
 * and run `npm run build`. npm test fails if this drifts.
 *
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */

import type { SVGProps } from 'react';
import type { IconLookup } from '../kapehan-icons.js';

export interface KapeIconProps extends Omit<SVGProps<SVGSVGElement>, 'name'> {
  /** Pixel size of the square viewport. Defaults to 24. */
  size?: number;
  /** Draw in one colour, inheriting currentColor. */
  mono?: boolean;
  /** Accepted and ignored; recolour with CSS instead. */
  colour?: string;
  /** An accessible name. Without it the icon is aria-hidden. */
  label?: string;
}

export type KapeIconComponent = (props: KapeIconProps) => JSX.Element;

/** Render any icon by name. */
export declare function KapeIcon(props: KapeIconProps & { name: IconLookup }): JSX.Element;

export declare const Espresso: KapeIconComponent;
export declare const Americano: KapeIconComponent;
export declare const Latte: KapeIconComponent;
export declare const Macchiato: KapeIconComponent;
export declare const Cappuccino: KapeIconComponent;
export declare const Mocha: KapeIconComponent;
export declare const Barako: KapeIconComponent;
export declare const ColdBrew: KapeIconComponent;
export declare const Tablea: KapeIconComponent;
export declare const CoffeeCup: KapeIconComponent;
export declare const CoffeeBean: KapeIconComponent;
export declare const CoffeeSack: KapeIconComponent;
export declare const DripBag: KapeIconComponent;
export declare const StampCard: KapeIconComponent;
export declare const FrenchPress: KapeIconComponent;
export declare const PourOver: KapeIconComponent;
export declare const MokaPot: KapeIconComponent;
export declare const Aeropress: KapeIconComponent;
export declare const BarakoPot: KapeIconComponent;
export declare const Kettle: KapeIconComponent;
export declare const Grinder: KapeIconComponent;
export declare const EspressoMachine: KapeIconComponent;
export declare const Tea: KapeIconComponent;
export declare const Matcha: KapeIconComponent;
export declare const Salabat: KapeIconComponent;
export declare const HotChocolate: KapeIconComponent;
export declare const MilkTea: KapeIconComponent;
export declare const UbeLatte: KapeIconComponent;
export declare const MangoShake: KapeIconComponent;
export declare const BukoJuice: KapeIconComponent;
export declare const Calamansi: KapeIconComponent;
export declare const HaloHalo: KapeIconComponent;
export declare const SagoGulaman: KapeIconComponent;
export declare const BukoPandan: KapeIconComponent;
export declare const WatermelonShake: KapeIconComponent;
export declare const AvocadoShake: KapeIconComponent;
export declare const PineappleJuice: KapeIconComponent;
export declare const Donut: KapeIconComponent;
export declare const CakeSlice: KapeIconComponent;
export declare const Croissant: KapeIconComponent;
export declare const Pandesal: KapeIconComponent;
export declare const Ensaymada: KapeIconComponent;
