/**
 * Every Kapehan React export: 42 icons and 30 components.
 *
 *   import { KapeButton, Barako } from 'kapehan/react';
 *
 * Importing this pulls both halves. Reach for kapehan/react/icons.js on its own when a
 * project only wants icons.
 *
 * GENERATED by scripts/generators/react.mjs. Do not edit by hand.
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */
export * from './icons.js';
export * from './components.js';
