/**
 * Finds the generators.
 *
 * Everything the package ships is generated by a module in scripts/generators/. They are
 * discovered from the directory rather than listed here, so adding one is adding a file and
 * touching nothing shared. That matters because every planned piece of work (React, Vue,
 * Blazor, doodles, types, the Tailwind variants) adds a generator, and when they all edited
 * one artifacts() function they collided on it. PR #5 rebasing onto #3 conflicted on exactly
 * this file and check.mjs, each side having added a different block at the same anchor.
 *
 * A generator module exports:
 *
 *   name       string, for error messages
 *   artifacts  async () => Map<repoRelativePath, contents>   what it writes
 *   pkg        optional { exports?: {}, files?: [] }         what package.json must carry
 *   check      optional async (ctx) => string[]              its own gates, ctx = { root, artifacts }
 *
 * Order is alphabetical and must not matter: two generators writing the same path is an
 * error, not a last-one-wins.
 */
import { readdir } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

export const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const DIR = join(root, 'scripts/generators');

export async function loadGenerators() {
  const files = (await readdir(DIR)).filter((f) => f.endsWith('.mjs')).sort();
  const mods = [];
  for (const f of files) {
    const mod = await import(join(DIR, f));
    if (typeof mod.artifacts !== 'function') throw new Error(`scripts/generators/${f} exports no artifacts()`);
    mods.push({ file: f, name: mod.name ?? f.replace('.mjs', ''), ...mod });
  }
  if (!mods.length) throw new Error('scripts/generators/ is empty, nothing would be built');
  return mods;
}

/**
 * Every generated file, merged. Two generators claiming one path is a collision that would
 * otherwise resolve silently by directory order, so it throws.
 */
export async function allArtifacts(generators) {
  const out = new Map();
  const owner = new Map();
  for (const g of generators) {
    for (const [path, body] of await g.artifacts()) {
      if (owner.has(path)) throw new Error(`${g.name} and ${owner.get(path)} both write ${path}`);
      owner.set(path, g.name);
      out.set(path, body);
    }
  }
  return out;
}

/**
 * What package.json must carry, according to the generators themselves.
 *
 * exports and files were not enough. Three generators independently needed a
 * peerDependency (react, vue) or a sideEffects entry (kape-doodle.js exists only to call
 * customElements.define, and a bundler will tree-shake it away without one), and could not
 * declare either. The gate then named the four exports, stayed silent about the peer, and
 * a consumer running `npm i kapehan` and importing kapehan/react would have hit
 * ERR_MODULE_NOT_FOUND with no warning. A gate that names three of four missing things
 * teaches people the list is complete.
 */
export function requiredPkg(generators) {
  const exports = {};
  const files = new Set();
  const peerDependencies = {};
  const peerDependenciesMeta = {};
  const sideEffects = new Set();

  for (const g of generators) {
    Object.assign(exports, g.pkg?.exports ?? {});
    for (const f of g.pkg?.files ?? []) files.add(f);
    Object.assign(peerDependencies, g.pkg?.peerDependencies ?? {});
    Object.assign(peerDependenciesMeta, g.pkg?.peerDependenciesMeta ?? {});
    for (const f of g.pkg?.sideEffects ?? []) sideEffects.add(f);
  }
  return { exports, files: [...files], peerDependencies, peerDependenciesMeta, sideEffects: [...sideEffects] };
}
