/**
 * Kapehan components for Vue: 30 render functions, no SFC compilation.
 *
 *   import { KapeButton } from 'kapehan/vue/components.js';
 *   import 'kapehan/kapehan.css';
 *
 * Every component is a plain object with props, emits and a setup() that returns an h()
 * closure, so it imports in node, in Vite with no plugin, and from a bare
 * <script type="module">. vue is a peer dependency and is never bundled.
 *
 * The class names are exactly the ones in kapehan.css. Nothing here holds a colour: the
 * stylesheet reads var(--accent) and friends, and swapping a palette restyles all of it.
 * No component fetches anything.
 *
 * Props and emits are derived from the <script setup> snippets in kapehan-components.js,
 * which are the specification. Those snippets ship untouched as vue/src/*.vue, as copy
 * material rather than as modules to import.
 *
 * GENERATED by scripts/generators/vue.mjs. Do not edit by hand.
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */
import { h, ref, computed, watch, onMounted, onBeforeUnmount, nextTick, useId, getCurrentInstance } from 'vue';
import { KapeIcon } from './icons.js';

/**
 * v-model that also works with no v-model bound.
 *
 * A caller who never binds modelValue still gets a working control, because the value is
 * held locally and the parent is only notified. Without the local copy an unbound
 * <KapeSeg /> is dead on click, which is how these read in a docs page.
 *
 * Who owns the value is decided the way Vue's own useModel decides it: by looking at the
 * raw vnode props for BOTH modelValue and an update:modelValue listener. If the parent
 * bound a real v-model it owns the value outright, and the child renders whatever came
 * back down, including nothing, when the parent validates or debounces and rejects the
 * update. Keeping a local copy and syncing it only on a prop change got that backwards:
 * the child moved to a value the parent never accepted and stayed there.
 */
const useModel = (props, emit, seed) => {
  const vm = getCurrentInstance();
  const owned = () => {
    const raw = vm && vm.vnode && vm.vnode.props;
    return !!raw && 'modelValue' in raw
      && ('onUpdate:modelValue' in raw || 'onUpdate:model-value' in raw);
  };
  const local = ref(props.modelValue !== undefined ? props.modelValue : seed);
  watch(() => props.modelValue, (v) => { if (v !== undefined) local.value = v; });
  return computed({
    get: () => (owned() ? props.modelValue : local.value),
    set: (v) => {
      if (!owned()) local.value = v;
      emit('update:modelValue', v);
    },
  });
};

/**
 * Button (Actions).
 *
 * Props: label, variant, icon, disabled
 * Emits: click
 * Keys: Enter or Space activates
 * Keys: Tab moves in and out
 */
export const KapeButton = {
  name: 'KapeButton',
  props: {
    label: { type: String, default: "Order now" },
    variant: { type: String, default: "default" },
    icon: { type: String, default: null },
    disabled: Boolean,
  },
  emits: ["click"],
  setup(props, { emit, slots }) {
    return () => h('button', {
      class: ['kape-btn', { 'kape-btn--primary': props.variant === 'primary', 'kape-btn--ghost': props.variant === 'ghost' }],
      type: 'button',
      disabled: props.disabled,
      onClick: (e) => emit('click', e),
    }, [
      props.icon ? h(KapeIcon, { name: props.icon, size: 20 }) : null,
      h('span', null, props.label),
    ]);
  },
};

/**
 * Chips (Actions).
 *
 * Props: options, modelValue
 * Emits: change, update:modelValue
 * Keys: Tab steps through chips
 * Keys: Enter or Space presses one
 */
export const KapeChip = {
  name: 'KapeChip',
  props: {
    options: { type: Array, default: () => ["All", "Hot", "Iced"] },
    modelValue: { type: String },
  },
  emits: ["change","update:modelValue"],
  setup(props, { emit, slots }) {
    const pick = useModel(props, emit, props.options[0]);
    // The seed is options[0], so a list that changes under an unbound chip row must not
    // leave the pressed chip pointing at a label that is no longer rendered.
    watch(() => props.options, (list) => { if (!list.includes(pick.value)) pick.value = list[0]; });

    return () => props.options.map((c) => h('button', {
      key: c,
      class: 'kape-chip',
      type: 'button',
      'aria-pressed': pick.value === c,
      onClick: () => { pick.value = c; emit('change', c); },
    }, c));
  },
};

/**
 * Input (Forms).
 *
 * Props: placeholder, icon, type, modelValue
 * Emits: update:modelValue
 * Keys: Tab focuses the field; the wrapper takes the focus ring via :focus-within
 */
export const KapeInput = {
  name: 'KapeInput',
  props: {
    placeholder: { type: String, default: "Search the menu" },
    icon: { type: String, default: "grinder" },
    type: { type: String, default: "search" },
    modelValue: { type: String, default: "" },
  },
  emits: ["update:modelValue"],
  setup(props, { emit, slots }) {
    const model = useModel(props, emit, '');

    return () => h('label', { class: 'kape-input' }, [
      props.icon ? h(KapeIcon, { name: props.icon, size: 18 }) : null,
      h('input', {
        type: props.type,
        placeholder: props.placeholder,
        value: model.value == null ? '' : model.value,
        onInput: (e) => { model.value = e.target.value; },
      }),
    ]);
  },
};

/**
 * Segmented (Actions).
 *
 * Props: options, modelValue
 * Emits: change, update:modelValue
 * Keys: Tab into the group, Enter or Space to pick
 * Keys: Arrow keys are not bound; segments are buttons, not a radiogroup
 */
export const KapeSeg = {
  name: 'KapeSeg',
  props: {
    options: { type: Array, default: () => ["Pick up", "Deliver"] },
    modelValue: { type: String, default: "Pick up" },
  },
  emits: ["change","update:modelValue"],
  setup(props, { emit, slots }) {
    const mode = useModel(props, emit, props.options[0]);

    return () => h('div', { class: 'kape-seg', role: 'group', 'aria-label': 'Fulfilment' },
      props.options.map((m) => h('button', {
        key: m,
        type: 'button',
        'aria-pressed': mode.value === m,
        onClick: () => { mode.value = m; emit('change', m); },
      }, m)));
  },
};

/**
 * Toast (Feedback).
 *
 * Props: message, tone, actionLabel, timeout
 * Emits: action, close
 * Keys: Tab reaches the action while the toast is mounted
 */
export const KapeToast = {
  name: 'KapeToast',
  props: {
    message: String,
    tone: { type: String, default: "info" },
    actionLabel: { type: String, default: null },
    timeout: { type: Number, default: 6000 },
  },
  emits: ["action","close"],
  setup(props, { emit, slots }) {
    // Cleared on unmount: a toast that unmounts before its timeout would otherwise emit
    // close into a dead component, and in a list of toasts that fires once per dismissal.
    let timer = null;
    onMounted(() => {
      if (props.timeout > 0 && props.tone !== 'warn') timer = setTimeout(() => emit('close'), props.timeout);
    });
    onBeforeUnmount(() => { if (timer) clearTimeout(timer); });

    return () => h('div', {
      class: ['kape-toast', { 'kape-toast--warn': props.tone === 'warn' }],
      role: props.tone === 'warn' ? 'alert' : 'status',
    }, [
      h(KapeIcon, { name: props.tone === 'warn' ? 'coffee-bean' : 'coffee-cup', size: 20 }),
      h('span', { class: 'kape-toast__text' }, props.message),
      props.actionLabel
        ? h('button', { class: 'kape-toast__action', type: 'button', onClick: () => emit('action') }, props.actionLabel)
        : null,
    ]);
  },
};

/**
 * Stamp card (Feedback).
 *
 * Props: total, filled, label, icon
 * Keys: Not focusable; it is a readout, not a control
 */
export const KapeStamps = {
  name: 'KapeStamps',
  props: {
    total: { type: Number, default: 10 },
    filled: { type: Number, default: 0 },
    label: { type: String, default: "Loyalty card" },
    icon: { type: String, default: "coffee-bean" },
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => [
      h('div', { class: 'kape-stamps', role: 'group', 'aria-label': props.label },
        Array.from({ length: props.total }, (_, i) => i + 1).map((i) => h('span', {
          key: i,
          'data-on': i <= props.filled ? '' : null,
          'aria-hidden': 'true',
        }, i <= props.filled ? [h(KapeIcon, { name: props.icon, size: 16 })] : null))),
      // The row above is aria-hidden, so the count is the only thing announced.
      h('p', { class: 'kape-sr' }, props.filled + ' of ' + props.total + ' stamps earned'),
    ];
  },
};

/**
 * Menu row (Data).
 *
 * Props: items, badge
 * Emits: pick
 * Keys: Only interactive rows take focus; do not put tabindex on a static row
 */
export const KapeRow = {
  name: 'KapeRow',
  props: {
    items: { type: Array, default: () => [] },
    badge: { type: String, default: null },
  },
  emits: ["pick"],
  setup(props, { emit, slots }) {
    return () => props.items.map((d) => h('div', {
      key: d.id,
      class: 'kape-row',
      onClick: () => emit('pick', d),
    }, [
      h('span', { class: 'kape-row__art' }, [h(KapeIcon, { name: d.icon, size: 40 })]),
      h('div', { class: 'kape-row__body' }, [
        h('p', { class: 'kape-row__title' }, [
          h('span', null, d.name),
          // The item carries its own badge; the prop is the fallback for a list where the
          // same flag applies to every row ("New", "Seasonal").
          d.badge || props.badge ? h('span', { class: 'kape-badge' }, d.badge || props.badge) : null,
        ]),
        h('p', { class: 'kape-row__sub' }, d.sub),
      ]),
      h('span', { class: 'kape-row__price' }, d.price),
    ]));
  },
};

/**
 * Stepper (Forms).
 *
 * Props: min, max, modelValue
 * Emits: change, update:modelValue
 * Keys: Enter or Space on either button
 * Keys: Arrow Up and Arrow Down step while the group has focus
 */
export const KapeStepper = {
  name: 'KapeStepper',
  props: {
    min: { type: Number, default: 1 },
    max: { type: Number, default: 99 },
    modelValue: { type: Number, default: 1 },
  },
  emits: ["change","update:modelValue"],
  setup(props, { emit, slots }) {
    const qty = useModel(props, emit, props.min);
    const step = (n) => {
      const next = Math.min(props.max, Math.max(props.min, Number(qty.value) + n));
      if (next === qty.value) return;
      qty.value = next;
      emit('change', next);
    };
    const onKeydown = (e) => {
      if (e.key === 'ArrowUp') { e.preventDefault(); step(1); }
      else if (e.key === 'ArrowDown') { e.preventDefault(); step(-1); }
    };

    return () => h('div', { class: 'kape-stepper', onKeydown }, [
      h('button', { type: 'button', 'aria-label': 'Fewer', disabled: qty.value <= props.min, onClick: () => step(-1) }, '\u2212'),
      h('output', { 'aria-live': 'polite' }, String(qty.value)),
      h('button', { type: 'button', 'aria-label': 'More', disabled: qty.value >= props.max, onClick: () => step(1) }, '+'),
    ]);
  },
};

/**
 * Switch (Actions).
 *
 * Props: label, disabled, modelValue
 * Emits: update:modelValue
 * Keys: Space toggles
 * Keys: Tab focuses the input, which is visually hidden but not display:none
 */
export const KapeSwitch = {
  name: 'KapeSwitch',
  props: {
    label: String,
    disabled: Boolean,
    modelValue: { type: Boolean, default: false },
  },
  emits: ["update:modelValue"],
  setup(props, { emit, slots }) {
    const on = useModel(props, emit, false);

    return () => [
      h('label', { class: 'kape-switch' }, [
        h('input', {
          type: 'checkbox',
          checked: !!on.value,
          disabled: props.disabled,
          'aria-label': props.label,
          onChange: (e) => { on.value = e.target.checked; },
        }),
      ]),
      h('span', null, props.label),
    ];
  },
};

/**
 * Checkbox · Radio (Forms).
 *
 * Props: options, mode, name, modelValue
 * Emits: update:modelValue
 * Keys: Radio: arrow keys move and select within the group
 * Keys: Checkbox: Space toggles, Tab moves
 */
export const KapeCheck = {
  name: 'KapeCheck',
  props: {
    options: { type: Array, default: () => ["12 oz", "16 oz"] },
    mode: { type: String, default: "radio" },
    name: { type: String, required: true },
    modelValue: {},
  },
  emits: ["update:modelValue"],
  setup(props, { emit, slots }) {
    const many = () => props.mode !== 'radio';
    const model = useModel(props, emit, many() ? [] : null);
    const list = () => (Array.isArray(model.value) ? model.value : []);
    const isOn = (s) => (many() ? list().includes(s) : model.value === s);
    const toggle = (s) => {
      if (!many()) { model.value = s; return; }
      model.value = list().includes(s) ? list().filter((x) => x !== s) : [...list(), s];
    };

    return () => props.options.map((s) => h('label', {
      key: s,
      class: many() ? 'kape-check' : 'kape-radio',
    }, [
      h('input', { type: props.mode, name: props.name, value: s, checked: isOn(s), onChange: () => toggle(s) }),
      h('span', null, s),
    ]));
  },
};

/**
 * Select (Forms).
 *
 * Props: options, modelValue, label
 * Emits: update:modelValue
 * Keys: Native: arrows open and move, Enter commits, Escape reverts
 */
export const KapeSelect = {
  name: 'KapeSelect',
  props: {
    options: { type: Array, default: () => [] },
    modelValue: { type: String },
    label: { type: String, required: true },
  },
  emits: ["update:modelValue"],
  setup(props, { emit, slots }) {
    const model = useModel(props, emit, undefined);

    return () => h('label', { class: 'kape-select' }, [
      // The label element wraps the select, so its text is the accessible name. Without it
      // the control announces as "combo box" and nothing else.
      props.label ? h('span', null, props.label) : null,
      h('select', {
        value: model.value,
        onChange: (e) => { model.value = e.target.value; },
      }, props.options.map((b) => h('option', {
        key: b.id,
        value: b.id,
        // Set on the option as well as the select: without it a server-rendered select
        // comes back with nothing chosen, because value is a property, not an attribute.
        selected: b.id === model.value,
      }, b.name))),
    ]);
  },
};

/**
 * Tabs (Navigation).
 *
 * Props: tabs, modelValue
 * Emits: change, update:modelValue
 * Keys: Arrow Left and Arrow Right move selection
 * Keys: Home and End jump to the first and last tab
 */
export const KapeTabs = {
  name: 'KapeTabs',
  props: {
    tabs: { type: Array, default: () => ["Menu", "Beans", "Our shop"] },
    modelValue: { type: String, default: "Menu" },
  },
  emits: ["change","update:modelValue"],
  setup(props, { emit, slots }) {
    const tab = useModel(props, emit, props.tabs[0]);
    const go = (t) => { if (t !== undefined && t !== tab.value) { tab.value = t; emit('change', t); } };
    const move = (n) => {
      const i = props.tabs.indexOf(tab.value);
      go(props.tabs[(i + n + props.tabs.length) % props.tabs.length]);
    };
    const onKeydown = (e) => {
      if (e.key === 'ArrowLeft') { e.preventDefault(); move(-1); }
      else if (e.key === 'ArrowRight') { e.preventDefault(); move(1); }
      else if (e.key === 'Home') { e.preventDefault(); go(props.tabs[0]); }
      else if (e.key === 'End') { e.preventDefault(); go(props.tabs[props.tabs.length - 1]); }
    };

    return () => h('div', { class: 'kape-tabs', role: 'tablist', onKeydown },
      props.tabs.map((t) => h('button', {
        key: t,
        type: 'button',
        role: 'tab',
        'aria-selected': tab.value === t,
        tabindex: tab.value === t ? 0 : -1,
        onClick: () => go(t),
      }, t)));
  },
};

/**
 * Card (Data).
 *
 * Props: item, size
 * Emits: add
 * Keys: Only the Add button takes focus; the whole card is not clickable
 */
export const KapeCard = {
  name: 'KapeCard',
  props: {
    item: { type: Object, required: true },
    size: { type: Number, default: 64 },
  },
  emits: ["add"],
  setup(props, { emit, slots }) {
    return () => h('article', { class: 'kape-card' }, [
      h(KapeIcon, { name: props.item.icon, size: props.size }),
      h('p', { class: 'kape-card__title' }, props.item.name),
      h('p', { class: 'kape-card__sub' }, [
        h('span', null, props.item.size),
        ' \u00b7 ',
        h('span', null, props.item.temp),
      ]),
      h('div', { class: 'kape-card__foot' }, [
        h('span', { class: 'kape-row__price' }, props.item.price),
        h('button', {
          class: ['kape-btn', 'kape-btn--primary'],
          type: 'button',
          onClick: () => emit('add', props.item),
        }, 'Add'),
      ]),
    ]);
  },
};

/**
 * Badge (Data).
 *
 * Props: label, tone
 * Keys: Not focusable
 */
export const KapeTag = {
  name: 'KapeTag',
  props: {
    label: String,
    tone: { type: String, default: "default" },
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => h('span', {
      class: ['kape-tag', { 'kape-tag--accent': props.tone === 'accent', 'kape-tag--ink': props.tone === 'ink' }],
    }, props.label);
  },
};

/**
 * Avatar (Navigation).
 *
 * Props: people, max, accentIndex
 * Keys: Not focusable unless each avatar links to a profile
 */
export const KapeAvatar = {
  name: 'KapeAvatar',
  props: {
    people: { type: Array, default: () => [] },
    max: { type: Number, default: 2 },
    accentIndex: { type: Number, default: null },
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => h('div', { class: 'kape-avatars' }, [
      ...props.people.slice(0, props.max).map((c, i) => h('span', {
        key: c.id,
        class: ['kape-avatar', { 'kape-avatar--accent': i === props.accentIndex }],
      }, c.initials)),
      props.people.length > props.max
        ? h('span', { class: 'kape-avatar', title: (props.people.length - props.max) + ' more' }, '+' + (props.people.length - props.max))
        : null,
    ]);
  },
};

/**
 * Dialog (Feedback).
 *
 * Props: open, title, body, confirmLabel
 * Emits: close, confirm
 * Keys: Escape closes (native)
 * Keys: Tab is trapped inside while modal (native)
 */
export const KapeDialog = {
  name: 'KapeDialog',
  props: {
    open: Boolean,
    title: String,
    body: String,
    confirmLabel: { type: String, default: "Confirm" },
  },
  emits: ["close","confirm"],
  setup(props, { emit, slots }) {
    const el = ref(null);
    // Per instance, never a fixed string: two dialogs on one page emitted the same
    // id="kape-dialog-title" and every aria-labelledby resolved to whichever the browser
    // found first. useId() is stable across server render and hydration, which a module
    // counter is not.
    const titleId = useId() + '-title';
    // showModal() is what makes the backdrop, the focus trap and Escape real. Calling it on
    // an already-open dialog throws InvalidStateError, so both directions are guarded.
    const sync = (open) => {
      const d = el.value;
      if (!d || typeof d.showModal !== 'function') return;
      if (open && !d.open) d.showModal();
      else if (!open && d.open) d.close();
    };
    onMounted(() => sync(props.open));
    watch(() => props.open, sync);

    return () => h('dialog', {
      ref: el,
      class: 'kape-dialog',
      'aria-labelledby': titleId,
      onClose: () => emit('close'),
      onCancel: () => emit('close'),
    }, [
      h('h2', { id: titleId }, props.title),
      h('p', null, props.body),
      h('div', { class: 'kape-dialog__actions' }, [
        h('button', { class: ['kape-btn', 'kape-btn--ghost'], type: 'button', autofocus: true, onClick: () => emit('close') }, 'Keep it'),
        h('button', { class: ['kape-btn', 'kape-btn--ink'], type: 'button', onClick: () => emit('confirm') }, props.confirmLabel),
      ]),
    ]);
  },
};

/**
 * Tooltip (Navigation).
 *
 * Props: text, placement
 * Keys: Shows on :focus-visible as well as hover, so keyboard users get it
 * Keys: Escape does not dismiss a CSS tooltip; keep tips non-blocking
 */
export const KapeTip = {
  name: 'KapeTip',
  props: {
    text: { type: String, required: true },
    placement: { type: String, default: "top" },
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => h('button', {
      class: ['kape-btn', 'kape-tip'],
      type: 'button',
      'data-tip': props.text,
      'data-placement': props.placement,
    }, slots.default ? slots.default() : null);
  },
};

/**
 * Skeleton (Data).
 *
 * Props: lines, width, loading
 * Keys: Skeletons are never focusable; keep tab order stable when they swap out
 */
export const KapeSkeleton = {
  name: 'KapeSkeleton',
  props: {
    lines: { type: Number, default: 3 },
    width: { type: String, default: "60%" },
    loading: { type: Boolean, default: true },
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => h('div', { 'aria-busy': props.loading }, props.loading
      ? Array.from({ length: props.lines }, (_, i) => h('span', { key: i, class: 'kape-skeleton', style: { width: props.width } }))
      : (slots.default ? slots.default() : null));
  },
};

/**
 * Progress (Feedback).
 *
 * Props: value, label
 * Keys: Not focusable; it reports, it does not accept input
 */
export const KapeProgress = {
  name: 'KapeProgress',
  props: {
    value: { type: Number, default: 0 },
    label: String,
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => h('span', {
      class: 'kape-progress',
      role: 'progressbar',
      'aria-valuenow': props.value,
      'aria-valuemin': 0,
      'aria-valuemax': 100,
      'aria-label': props.label,
    }, [h('span', { style: { width: props.value + '%' } })]);
  },
};

/**
 * Pagination (Navigation).
 *
 * Props: page, pages
 * Emits: change
 * Keys: Tab through the numbers
 * Keys: Enter or Space activates; arrow keys are left to the browser
 */
export const KapePager = {
  name: 'KapePager',
  props: {
    page: { type: Number, default: 1 },
    pages: { type: Number, default: 1 },
  },
  emits: ["change"],
  setup(props, { emit, slots }) {
    const list = computed(() => Array.from({ length: props.pages }, (_, i) => i + 1));

    return () => h('nav', { class: 'kape-pager', 'aria-label': 'Pages' }, [
      h('button', { type: 'button', 'aria-label': 'Previous', disabled: props.page === 1, onClick: () => emit('change', props.page - 1) }, '\u2039'),
      ...list.value.map((p) => h('button', {
        key: p,
        type: 'button',
        'aria-current': p === props.page ? 'page' : undefined,
        onClick: () => emit('change', p),
      }, String(p))),
      h('button', { type: 'button', 'aria-label': 'Next', disabled: props.page === props.pages, onClick: () => emit('change', props.page + 1) }, '\u203a'),
    ]);
  },
};

/**
 * Accordion (Data).
 *
 * Props: items, openFirst
 * Keys: Enter or Space toggles a summary
 * Keys: Tab moves between summaries
 */
export const KapeAcc = {
  name: 'KapeAcc',
  props: {
    items: { type: Array, default: () => [] },
    openFirst: Boolean,
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => props.items.map((f, i) => h('details', {
      key: f.id,
      class: 'kape-acc',
      open: Boolean(props.openFirst && i === 0),
    }, [
      h('summary', null, f.q),
      h('p', null, f.a),
    ]));
  },
};

/**
 * Table (Data).
 *
 * Props: rows, caption, numericColumns
 * Keys: Table content is read in DOM order; keep the money column last in both markup and layout
 */
export const KapeTable = {
  name: 'KapeTable',
  props: {
    rows: { type: Array, default: () => [] },
    caption: String,
    numericColumns: { type: Array, default: () => [] },
  },
  emits: [],
  setup(props, { emit, slots }) {
    const HEADS = ['Order', 'Items', 'Status', 'Total'];
    // An empty numericColumns keeps the money column mono and right-aligned, which is what
    // the table did before the prop was wired, so the default is not a behaviour change.
    const numeric = (col) => (props.numericColumns.length ? props.numericColumns.includes(col) : col === 'Total');
    const numClass = (col) => (numeric(col) ? 'num' : undefined);

    return () => h('table', { class: 'kape-table' }, [
      h('caption', { class: 'kape-sr' }, props.caption),
      h('thead', null, [h('tr', null,
        HEADS.map((col) => h('th', { key: col, scope: 'col', class: numClass(col) }, col)))]),
      h('tbody', null, props.rows.map((o) => h('tr', { key: o.id }, [
        h('td', { class: numClass('Order') }, ['#', h('span', null, String(o.id))]),
        h('td', { class: numClass('Items') }, o.summary),
        h('td', { class: numClass('Status') }, [h('span', { class: ['kape-tag', { 'kape-tag--accent': o.status === 'making' }] }, o.status)]),
        h('td', { class: numClass('Total') }, o.total),
      ]))),
    ]);
  },
};

/**
 * Breadcrumb (Navigation).
 *
 * Props: trail, label
 * Keys: Tab through the ancestor links only
 */
export const KapeCrumbs = {
  name: 'KapeCrumbs',
  props: {
    trail: { type: Array, default: () => [] },
    label: { type: String, default: "Breadcrumb" },
  },
  emits: [],
  setup(props, { emit, slots }) {
    return () => h('nav', { 'aria-label': props.label }, [
      h('ol', { class: 'kape-crumbs' }, props.trail.map((t, i) => h('li', {
        key: t.href,
        'aria-current': i === props.trail.length - 1 ? 'page' : undefined,
      }, [
        i < props.trail.length - 1 ? h('a', { href: t.href }, t.label) : h('span', null, t.label),
      ]))),
    ]);
  },
};

/**
 * File upload (Forms).
 *
 * Props: accept, maxSize, files
 * Emits: cancel, files
 * Keys: Tab focuses the input, Enter or Space opens the picker
 * Keys: Drag and drop is an enhancement, never the only path
 */
export const KapeUpload = {
  name: 'KapeUpload',
  props: {
    accept: { type: String, default: ".csv,.xlsx" },
    maxSize: { type: Number, default: 10485760 },
    files: { type: Array, default: () => [] },
  },
  emits: ["cancel","files"],
  setup(props, { emit, slots }) {
    const over = ref(false);
    const take = (list) => {
      if (!list) return;
      emit('files', Array.from(list).filter((f) => f.size <= props.maxSize));
    };

    return () => [
      h('label', {
        class: ['kape-drop', { 'is-over': over.value }],
        onDragover: (e) => { e.preventDefault(); over.value = true; },
        onDragleave: () => { over.value = false; },
        onDrop: (e) => { e.preventDefault(); over.value = false; take(e.dataTransfer && e.dataTransfer.files); },
      }, [
        h(KapeIcon, { name: 'coffee-sack', size: 36 }),
        h('strong', null, 'Drop the menu sheet here'),
        h('span', null, ['CSV or XLSX, up to 10 MB. Or ', h('u', null, 'browse'), '.']),
        h('input', { type: 'file', accept: props.accept, hidden: true, onChange: (e) => take(e.target.files) }),
      ]),
      ...props.files.map((f) => h('div', { key: f.name, class: 'kape-file' }, [
        h('span', { class: 'kape-file__ext' }, f.ext),
        h('div', { class: 'kape-file__body' }, [
          h('span', null, f.name),
          h('span', {
            class: 'kape-progress',
            role: 'progressbar',
            'aria-valuenow': f.pct,
            'aria-label': 'Uploading ' + f.name,
          }, [h('span', { style: { width: f.pct + '%' } })]),
        ]),
        h('button', { type: 'button', 'aria-label': 'Cancel', onClick: () => emit('cancel', f) }, '\u00d7'),
      ])),
    ];
  },
};

/**
 * Editable table (Data).
 *
 * Props: rows, editingId, columns
 * Emits: save
 * Keys: Enter commits, Escape reverts and returns focus to the cell
 * Keys: F2 or double-click enters edit mode
 * Keys: Tab out commits, matching spreadsheet behaviour
 */
export const KapeEdit = {
  name: 'KapeEdit',
  props: {
    rows: { type: Array, default: () => [] },
    editingId: { type: String, default: null },
    columns: { type: Array, default: () => [] },
  },
  emits: ["save"],
  setup(props, { emit, slots }) {
    const HEADS = ['Drink', 'Size', 'Price', 'Stock'];
    const heads = computed(() => (props.columns.length ? props.columns : HEADS));
    // Price and Stock are the mono columns in the default layout; renaming the headers
    // keeps the same two positions rather than guessing from the new words.
    const headClass = (i) => (i >= 2 ? 'num' : undefined);

    const own = ref(null);
    // Controlled when editingId is passed, self-owned when it is not, which is exactly
    // what "leave unset to let the component own it" says in the props table.
    const controlled = () => props.editingId !== null && props.editingId !== undefined;
    const editing = computed(() => (controlled() ? props.editingId : own.value));
    const draft = ref('');
    const field = ref(null);
    const status = ref('');
    const body = ref(null);

    // A roving tabindex over the rows. The F2 handler hangs on the <tr>, and a row that is
    // not being edited holds nothing focusable at all, so before this the key could never
    // be pressed: Tab skipped the table and F2 had no target. One tab stop for the whole
    // table, arrows move inside it, which is the grid pattern the other widgets use.
    const cursor = ref(0);
    const row = computed(() => Math.min(Math.max(0, cursor.value), Math.max(0, props.rows.length - 1)));
    const focusRow = async (i) => {
      cursor.value = i;
      await nextTick();
      const box = body.value;
      if (!box || !box.querySelector) return;
      const tr = box.querySelector('tr[tabindex="0"]');
      if (tr && tr.focus) tr.focus();
    };

    const start = async (d) => {
      if (editing.value === d.id) return;
      own.value = d.id;
      draft.value = String(d.price);
      await nextTick();
      const input = field.value;
      if (input && input.focus) { input.focus(); if (input.select) input.select(); }
    };
    // Enter and blur both land here, and blur fires after Enter has already committed, so
    // the id guard is what stops a second save emitting with a stale draft.
    const commit = (d) => {
      if (editing.value !== d.id) return;
      own.value = null;
      const n = Number(draft.value);
      if (draft.value.trim() === '' || Number.isNaN(n)) { status.value = 'Not a number, ' + d.name + ' unchanged'; return; }
      status.value = d.name + ' saved at ' + n;
      emit('save', d.id, n);
    };
    const cancel = () => {
      if (editing.value === null) return;
      own.value = null;
      status.value = 'Edit cancelled';
    };
    const onRowKeydown = (e, d, i) => {
      // While the cell input is open it owns the keyboard: arrows move the caret, not rows.
      if (editing.value === d.id) return;
      if (e.key === 'F2') { e.preventDefault(); cursor.value = i; start(d); }
      else if (e.key === 'ArrowDown') { e.preventDefault(); focusRow(Math.min(props.rows.length - 1, i + 1)); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); focusRow(Math.max(0, i - 1)); }
    };

    return () => [
      h('table', { class: ['kape-table', 'kape-table--edit'] }, [
        h('thead', null, [h('tr', null,
          heads.value.map((col, i) => h('th', { key: col, scope: 'col', class: headClass(i) }, col)))]),
        h('tbody', { ref: body }, props.rows.map((d, i) => h('tr', {
          key: d.id,
          class: { 'is-editing': editing.value === d.id },
          tabindex: i === row.value ? 0 : -1,
          onDblclick: () => { cursor.value = i; start(d); },
          onKeydown: (e) => onRowKeydown(e, d, i),
        }, [
          h('td', null, d.name),
          h('td', null, d.size),
          h('td', { class: 'num' }, [
            editing.value === d.id
              ? h('input', {
                  ref: field,
                  value: draft.value,
                  inputmode: 'numeric',
                  onInput: (e) => { draft.value = e.target.value; },
                  onKeydown: (e) => {
                    if (e.key === 'Enter') { e.preventDefault(); commit(d); }
                    else if (e.key === 'Escape') { e.preventDefault(); cancel(); }
                  },
                  onBlur: () => commit(d),
                })
              : h('span', null, d.price),
          ]),
          h('td', { class: 'num' }, [
            h('span', null, d.stock),
            editing.value === d.id
              ? h('button', {
                  class: ['kape-btn', 'kape-btn--sm'],
                  type: 'button',
                  // mousedown, not click: the input's blur would commit and unmount this
                  // button before a click ever landed on it.
                  onMousedown: (e) => { e.preventDefault(); commit(d); },
                }, 'Save')
              : null,
          ]),
        ]))),
      ]),
      h('p', { class: 'kape-sr', 'aria-live': 'polite' }, status.value),
    ];
  },
};

/**
 * Combobox (Forms).
 *
 * Props: options, placeholder, modelValue
 * Emits: change, update:modelValue
 * Keys: Arrow Down and Arrow Up move the active option
 * Keys: Enter toggles the active option and keeps the list open
 * Keys: Backspace on an empty field removes the last chip
 * Keys: Escape closes the list, Tab closes and moves on
 */
export const KapeCombo = {
  name: 'KapeCombo',
  props: {
    options: { type: Array, default: () => [] },
    placeholder: { type: String, default: "Add…" },
    modelValue: { type: Array, default: () => [] },
  },
  emits: ["change","update:modelValue"],
  setup(props, { emit, slots }) {
    const model = useModel(props, emit, []);
    // Per instance, for the same reason the dialog title is: two comboboxes on one page
    // both pointed aria-controls and aria-activedescendant at the first one's list.
    const uid = useId();
    const listId = uid + '-list';
    const optId = (id) => uid + '-opt-' + id;
    const q = ref('');
    const open = ref(false);
    const cursor = ref(0);

    const picked = () => (Array.isArray(model.value) ? model.value : []);
    const hits = computed(() => props.options.filter((a) => a.name.toLowerCase().includes(q.value.toLowerCase())));
    const byId = (id) => props.options.find((a) => a.id === id);
    // The filter can shrink under the cursor while the user types, and an out-of-range
    // cursor points aria-activedescendant at an id that is no longer in the DOM.
    watch(hits, () => { if (cursor.value >= hits.value.length) cursor.value = 0; });

    const toggle = (id) => {
      const next = picked().includes(id) ? picked().filter((x) => x !== id) : [...picked(), id];
      model.value = next;
      emit('change', next);
    };
    const move = (n) => {
      if (!hits.value.length) return;
      cursor.value = (cursor.value + n + hits.value.length) % hits.value.length;
    };
    const onKeydown = (e) => {
      if (e.key === 'ArrowDown') { e.preventDefault(); open.value = true; move(1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); move(-1); }
      else if (e.key === 'Enter' && open.value) {
        e.preventDefault();
        const hit = hits.value[cursor.value];
        if (hit) toggle(hit.id);
      } else if (e.key === 'Escape') { open.value = false; }
      else if (e.key === 'Tab') { open.value = false; }
      else if (e.key === 'Backspace' && !q.value && picked().length) {
        const next = picked().slice(0, -1);
        model.value = next;
        emit('change', next);
      }
    };

    return () => h('div', {
      class: 'kape-combo',
      role: 'combobox',
      'aria-expanded': open.value,
      'aria-haspopup': 'listbox',
      'aria-controls': listId,
    }, [
      h('div', { class: 'kape-combo__field' }, [
        ...picked().map((id) => h('span', { key: id, class: 'kape-chip' }, [
          h('span', null, byId(id) ? byId(id).name : id),
          h('button', { type: 'button', 'aria-label': 'Remove ' + (byId(id) ? byId(id).name : id), onClick: () => toggle(id) }, '\u00d7'),
        ])),
        h('input', {
          value: q.value,
          placeholder: props.placeholder,
          'aria-activedescendant': open.value && hits.value[cursor.value] ? optId(hits.value[cursor.value].id) : undefined,
          onInput: (e) => { q.value = e.target.value; open.value = true; },
          onFocus: () => { open.value = true; },
          onKeydown,
        }),
      ]),
      open.value
        ? h('ul', { id: listId, class: 'kape-combo__list', role: 'listbox', 'aria-multiselectable': 'true' },
            hits.value.map((a, i) => h('li', {
              id: optId(a.id),
              key: a.id,
              role: 'option',
              'aria-selected': picked().includes(a.id),
              class: { 'is-active': i === cursor.value },
              // mousedown with preventDefault, so the input never loses focus and
              // aria-activedescendant stays the thing that moves.
              onMousedown: (e) => { e.preventDefault(); toggle(a.id); },
            }, [
              h('span', null, a.name),
              h('small', null, '+' + a.price),
            ])))
        : null,
    ]);
  },
};

/**
 * Multi-select (Forms).
 *
 * Props: options, max, modelValue, summaryLabel
 * Emits: update:modelValue
 * Keys: Arrow keys move, Space or Enter toggles without closing
 * Keys: Escape closes, Home and End jump the list
 * Keys: Backspace removes the last chip when the field has focus
 */
export const KapeMulti = {
  name: 'KapeMulti',
  props: {
    options: { type: Array, default: () => [] },
    max: { type: Number, default: null },
    modelValue: { type: Array, default: () => [] },
    summaryLabel: { type: Function },
  },
  emits: ["update:modelValue"],
  setup(props, { emit, slots }) {
    const model = useModel(props, emit, []);
    // Per instance: two branch pickers on one page emitted id="kape-multi-list" and
    // id="kape-multi-count" twice, which is invalid HTML, and both aria-describedby
    // attributes then named the first one's count line.
    const uid = useId();
    const listId = uid + '-list';
    const countId = uid + '-count';
    const open = ref(false);
    const cursor = ref(0);

    const picked = () => (Array.isArray(model.value) ? model.value : []);
    const full = computed(() => props.max !== null && picked().length >= props.max);
    const byId = (id) => props.options.find((o) => o.id === id);
    const blocked = (id) => full.value && !picked().includes(id);

    const set = (next) => { model.value = next; };
    const toggle = (id) => {
      if (blocked(id)) return;
      set(picked().includes(id) ? picked().filter((x) => x !== id) : [...picked(), id]);
    };
    const move = (n) => {
      if (!props.options.length) return;
      cursor.value = (cursor.value + n + props.options.length) % props.options.length;
    };
    const onKeydown = (e) => {
      const k = e.key;
      if (k === 'ArrowDown') { e.preventDefault(); open.value = true; move(1); }
      else if (k === 'ArrowUp') { e.preventDefault(); move(-1); }
      else if (k === ' ' || k === 'Enter') {
        e.preventDefault();
        if (!open.value) { open.value = true; return; }
        const o = props.options[cursor.value];
        if (o) toggle(o.id);
      } else if (k === 'Home') { e.preventDefault(); cursor.value = 0; }
      else if (k === 'End') { e.preventDefault(); cursor.value = Math.max(0, props.options.length - 1); }
      else if (k === 'Escape') { open.value = false; }
      else if (k === 'Backspace' && picked().length) { e.preventDefault(); set(picked().slice(0, -1)); }
    };

    return () => h('div', {
      class: 'kape-combo',
      role: 'combobox',
      'aria-expanded': open.value,
      'aria-haspopup': 'listbox',
      'aria-controls': listId,
      'aria-describedby': countId,
    }, [
      h('div', {
        class: 'kape-combo__field',
        tabindex: 0,
        onKeydown,
        onClick: () => { open.value = !open.value; },
      }, [
        ...picked().map((id) => h('span', { key: id, class: 'kape-chip' }, [
          h('span', null, byId(id) ? byId(id).name : id),
          h('button', {
            type: 'button',
            'aria-label': 'Remove ' + (byId(id) ? byId(id).name : id),
            onClick: (e) => { e.stopPropagation(); toggle(id); },
          }, '\u00d7'),
        ])),
        picked().length ? null : h('span', { class: 'kape-combo__hint' }, 'Pick your branches'),
      ]),
      open.value
        ? h('ul', { id: listId, class: 'kape-combo__list', role: 'listbox', 'aria-multiselectable': 'true' },
            props.options.map((o, i) => h('li', {
              key: o.id,
              role: 'option',
              'aria-selected': picked().includes(o.id),
              // Blocked options stay in the list and stay announced: removing them at max
              // makes the list silently change length under a screen reader.
              'aria-disabled': blocked(o.id),
              class: { 'is-active': i === cursor.value },
              onMousedown: (e) => { e.preventDefault(); toggle(o.id); },
            }, o.name)))
        : null,
      h('p', { id: countId, class: 'kape-sr', 'aria-live': 'polite' },
        props.summaryLabel
          ? props.summaryLabel(picked().length)
          : picked().length + ' of ' + props.options.length + ' selected'),
    ]);
  },
};

/**
 * Date range (Forms).
 *
 * Props: from, to, month, presets
 * Emits: apply, cancel
 * Keys: Arrow keys move a day at a time, Page Up and Page Down a month
 * Keys: Enter picks the start, then the end; Escape reverts to the last applied range
 * Keys: Tab reaches presets, grid, then Cancel and Apply
 */
export const KapeRange = {
  name: 'KapeRange',
  props: {
    from: { type: Date, default: null },
    to: { type: Date, default: null },
    month: { type: Date, default: () => new Date() },
    presets: { type: Array, default: () => [] },
  },
  emits: ["apply","cancel"],
  setup(props, { emit, slots }) {
    const startOfMonth = (d) => new Date(d.getFullYear(), d.getMonth(), 1);
    const midnight = (d) => new Date(d.getFullYear(), d.getMonth(), d.getDate());
    const inMonth = (d, v) => d.getFullYear() === v.getFullYear() && d.getMonth() === v.getMonth();

    // month decides which page is drawn; from is only the focus seed when it lands on that
    // page. Seeding focus from `from || new Date()` regardless is what left
    // <KapeRange :month="new Date(2026, 0, 1)" /> with no tab stop at all: every rendered
    // day compared against a date in a different month, so all 31 buttons got tabindex=-1
    // and Tab skipped the grid entirely.
    const seedView = () => startOfMonth(props.month || props.from || new Date());
    const seedFocus = (v) => {
      for (const d of [props.from, new Date()]) if (d && inMonth(midnight(d), v)) return midnight(d);
      return v;
    };

    const open = ref(false);
    const view = ref(seedView());
    const draft = ref({ from: props.from, to: props.to });
    const focused = ref(seedFocus(view.value));
    const grid = ref(null);

    // Read once in setup() is read once forever. month, from and to are ordinary props a
    // parent changes after mount, and before this nothing watched any of them.
    watch(() => props.month, () => { view.value = seedView(); focused.value = seedFocus(view.value); });
    watch(() => [props.from, props.to], () => {
      draft.value = { from: props.from, to: props.to };
      if (!inMonth(focused.value, view.value)) focused.value = seedFocus(view.value);
    });

    const days = computed(() => {
      const first = view.value;
      const total = new Date(first.getFullYear(), first.getMonth() + 1, 0).getDate();
      return Array.from({ length: total }, (_, i) => new Date(first.getFullYear(), first.getMonth(), i + 1));
    });
    const at = (d) => (d ? midnight(d).getTime() : null);
    // Exactly one tab stop, always. If focus has drifted off the page being shown, the
    // first day of that page takes it rather than nothing taking it.
    const tabDay = computed(() => (inMonth(focused.value, view.value) ? at(focused.value) : at(days.value[0])));
    const sameDay = (a, b) => a !== null && b !== null && a === b;
    const today = midnight(new Date()).getTime();
    const classOf = (d) => {
      const t = at(d);
      const a = at(draft.value.from);
      const b = at(draft.value.to);
      return {
        'is-start': sameDay(t, a),
        'is-end': sameDay(t, b),
        'in-range': a !== null && b !== null && t > a && t < b,
      };
    };
    const isEnd = (d) => { const c = classOf(d); return c['is-start'] || c['is-end']; };
    const pick = (d) => {
      const from = draft.value.from;
      const to = draft.value.to;
      draft.value = from && !to && at(d) > at(from) ? { from, to: d } : { from: d, to: null };
    };
    const shift = (n) => {
      const next = new Date(focused.value);
      next.setDate(next.getDate() + n);
      focused.value = next;
      view.value = startOfMonth(next);
    };
    const shiftMonth = (n) => {
      const next = new Date(focused.value.getFullYear(), focused.value.getMonth() + n, 1);
      const last = new Date(next.getFullYear(), next.getMonth() + 1, 0).getDate();
      next.setDate(Math.min(focused.value.getDate(), last));
      focused.value = next;
      view.value = startOfMonth(next);
    };
    const refocus = async () => {
      await nextTick();
      const box = grid.value;
      if (!box || !box.querySelector) return;
      const btn = box.querySelector('[tabindex="0"]');
      if (btn && btn.focus) btn.focus();
    };
    const onKeydown = (e) => {
      const step = { ArrowLeft: -1, ArrowRight: 1, ArrowUp: -7, ArrowDown: 7 }[e.key];
      if (step) { e.preventDefault(); shift(step); refocus(); }
      else if (e.key === 'PageUp') { e.preventDefault(); shiftMonth(-1); refocus(); }
      else if (e.key === 'PageDown') { e.preventDefault(); shiftMonth(1); refocus(); }
      else if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); pick(focused.value); }
      else if (e.key === 'Escape') {
        e.preventDefault();
        draft.value = { from: props.from, to: props.to };
        open.value = false;
        emit('cancel');
      }
    };
    const fmt = (d) => (d ? d.toLocaleDateString('en-PH', { month: 'short', day: 'numeric', year: 'numeric' }) : '');
    const label = computed(() => (draft.value.from ? fmt(draft.value.from) + ' to ' + (draft.value.to ? fmt(draft.value.to) : '\u2026') : 'Pick a range'));

    return () => h('div', { class: 'kape-range' }, [
      h('button', {
        class: 'kape-range__trigger',
        type: 'button',
        'aria-expanded': open.value,
        onClick: () => { open.value = !open.value; },
      }, [
        h(KapeIcon, { name: 'stamp-card', size: 18 }),
        h('span', null, label.value),
      ]),

      open.value ? h('div', { class: 'kape-range__pop' }, [
        h('ul', { class: 'kape-range__presets' }, props.presets.map((p) => h('li', {
          key: p.label,
          'aria-current': at(draft.value.from) === at(p.from) && at(draft.value.to) === at(p.to) ? 'true' : undefined,
          onClick: () => { draft.value = { from: p.from, to: p.to }; },
        }, p.label))),

        h('div', { class: 'kape-cal', onKeydown }, [
          h('header', null, [
            h('button', { type: 'button', 'aria-label': 'Previous month', onClick: () => shiftMonth(-1) }, '\u2039'),
            h('span', null, view.value.toLocaleDateString('en-PH', { month: 'long', year: 'numeric' })),
            h('button', { type: 'button', 'aria-label': 'Next month', onClick: () => shiftMonth(1) }, '\u203a'),
          ]),
          h('div', { ref: grid, class: 'kape-cal__grid', role: 'group', 'aria-label': 'Days' },
            days.value.map((d) => h('button', {
              key: d.getTime(),
              type: 'button',
              class: classOf(d),
              'aria-label': fmt(d),
              'aria-current': at(d) === today ? 'date' : undefined,
              'aria-pressed': isEnd(d) ? true : undefined,
              // One tab stop for the whole grid: arrows move within it, Tab leaves it.
              tabindex: at(d) === tabDay.value ? 0 : -1,
              onClick: () => { focused.value = midnight(d); pick(d); },
            }, String(d.getDate())))),
        ]),

        h('footer', null, [
          h('button', {
            class: 'kape-btn',
            type: 'button',
            onClick: () => { draft.value = { from: props.from, to: props.to }; open.value = false; emit('cancel'); },
          }, 'Cancel'),
          h('button', {
            class: ['kape-btn', 'kape-btn--ink'],
            type: 'button',
            disabled: !draft.value.from || !draft.value.to,
            onClick: () => { open.value = false; emit('apply', draft.value); },
          }, 'Apply'),
        ]),
      ]) : null,
    ]);
  },
};

/**
 * Command palette (Overlays).
 *
 * Props: commands, open, hotkey, placeholder
 * Emits: update:open
 * Keys: Cmd K or Ctrl K opens and closes
 * Keys: Arrow Down and Arrow Up move the cursor, wrapping at the ends
 * Keys: Enter runs the active command, Escape closes and restores focus to the opener
 */
export const KapeCmdk = {
  name: 'KapeCmdk',
  props: {
    commands: { type: Array, default: () => [] },
    open: Boolean,
    hotkey: { type: String, default: "k" },
    placeholder: { type: String, default: "Type a command or search" },
  },
  emits: ["update:open"],
  setup(props, { emit, slots }) {
    const el = ref(null);
    const field = ref(null);
    // Per instance: id="kape-cmdk-list" and the per-command option ids were fixed strings.
    const uid = useId();
    const listId = uid + '-list';
    const cmdId = (id) => uid + '-cmd-' + id;
    const q = ref('');
    const cursor = ref(0);
    let opener = null;

    const hits = computed(() => props.commands.filter((c) => c.label.toLowerCase().includes(q.value.toLowerCase())));
    const groups = computed(() => [...new Set(hits.value.map((c) => c.group))]);

    // Bound in onMounted, not at module scope: window does not exist on a server, and this
    // package is imported by Nuxt before a browser is ever involved.
    const onHotkey = (e) => {
      if ((e.metaKey || e.ctrlKey) && e.key.toLowerCase() === props.hotkey) {
        e.preventDefault();
        opener = document.activeElement;
        emit('update:open', !props.open);
      }
    };
    const sync = async (open) => {
      const d = el.value;
      if (!d || typeof d.showModal !== 'function') return;
      if (open) {
        if (!d.open) d.showModal();
        q.value = '';
        cursor.value = 0;
        await nextTick();
        if (field.value && field.value.focus) field.value.focus();
      } else {
        if (d.open) d.close();
        if (opener && opener.focus) opener.focus();
      }
    };
    onMounted(() => { window.addEventListener('keydown', onHotkey); sync(props.open); });
    onBeforeUnmount(() => window.removeEventListener('keydown', onHotkey));
    watch(() => props.open, sync);
    watch(hits, () => { cursor.value = 0; });

    const move = (n) => {
      if (hits.value.length) cursor.value = (cursor.value + n + hits.value.length) % hits.value.length;
    };
    const run = (c) => {
      const cmd = c || hits.value[cursor.value];
      if (!cmd) return;
      emit('update:open', false);
      if (typeof cmd.run === 'function') cmd.run();
    };
    const onKeydown = (e) => {
      if (e.key === 'ArrowDown') { e.preventDefault(); move(1); }
      else if (e.key === 'ArrowUp') { e.preventDefault(); move(-1); }
      else if (e.key === 'Enter') { e.preventDefault(); run(); }
    };

    return () => h('dialog', {
      ref: el,
      class: 'kape-cmdk',
      'aria-label': 'Command palette',
      onClose: () => emit('update:open', false),
    }, [
      h('label', null, [
        h(KapeIcon, { name: 'grinder', size: 18 }),
        h('input', {
          ref: field,
          value: q.value,
          placeholder: props.placeholder,
          role: 'combobox',
          'aria-expanded': 'true',
          'aria-controls': listId,
          'aria-activedescendant': hits.value[cursor.value] ? cmdId(hits.value[cursor.value].id) : undefined,
          onInput: (e) => { q.value = e.target.value; },
          onKeydown,
        }),
        h('kbd', null, 'esc'),
      ]),

      h('ul', { id: listId, role: 'listbox' }, groups.value.flatMap((g) => [
        // presentation, not an option: a heading counted as an option makes the listbox
        // report the wrong size and lets the cursor land on a non-command.
        h('li', { key: 'g:' + g, class: 'kape-cmdk__group', role: 'presentation' }, g),
        ...hits.value.filter((c) => c.group === g).map((c) => h('li', {
          id: cmdId(c.id),
          key: c.id,
          role: 'option',
          'aria-selected': hits.value[cursor.value] ? hits.value[cursor.value].id === c.id : false,
          onMousedown: (e) => { e.preventDefault(); cursor.value = hits.value.indexOf(c); run(c); },
        }, [h('span', null, c.label)])),
      ])),

      h('footer', null, [
        h('kbd', null, '\u2191\u2193'), ' move ',
        h('kbd', null, '\u21b5'), ' run ',
        h('kbd', null, 'esc'), ' close',
        h('span', { class: 'kape-sr', 'aria-live': 'polite' }, hits.value.length + ' results'),
      ]),
    ]);
  },
};

/**
 * Drawer (Overlays).
 *
 * Props: open, title, lines, side
 * Emits: close, ready, refund
 * Keys: Escape closes (native)
 * Keys: Tab cycles inside the drawer only (native)
 * Keys: The footer actions are the last two stops, in destructive-last order
 */
export const KapeDrawer = {
  name: 'KapeDrawer',
  props: {
    open: Boolean,
    title: String,
    lines: { type: Array, default: () => [] },
    side: { type: String, default: "right" },
  },
  emits: ["close","ready","refund"],
  setup(props, { emit, slots }) {
    const el = ref(null);
    const closer = ref(null);
    // Per instance: a second drawer in the same tree duplicated id="kape-drawer-title".
    const titleId = useId() + '-title';
    let opener = null;

    const sync = async (open) => {
      const d = el.value;
      if (!d || typeof d.showModal !== 'function') return;
      if (open) {
        opener = document.activeElement;
        if (!d.open) d.showModal();
        await nextTick();
        if (closer.value && closer.value.focus) closer.value.focus();
      } else {
        if (d.open) d.close();
        if (opener && opener.focus) opener.focus();
      }
    };
    onMounted(() => sync(props.open));
    watch(() => props.open, sync);

    const total = () => props.lines.reduce((n, l) => n + Number(String(l.total).replace(/[^0-9.]/g, '')), 0);

    return () => h('dialog', {
      ref: el,
      class: 'kape-drawer',
      // The stylesheet pins the panel to the right edge; a left drawer flips the three
      // properties that decide the edge and nothing else.
      style: props.side === 'left' ? { inset: '0 auto 0 0', borderLeft: 0, borderRight: '1px solid var(--line)' } : null,
      'aria-labelledby': titleId,
      onClose: () => emit('close'),
      onCancel: () => emit('close'),
    }, [
      h('header', null, [
        h('span', { id: titleId }, props.title),
        h('button', { ref: closer, type: 'button', 'aria-label': 'Close', onClick: () => emit('close') }, '\u00d7'),
      ]),

      h('div', { class: 'kape-drawer__body' }, [
        ...props.lines.map((l) => h('div', { key: l.id, class: 'kape-line' }, [
          h('span', null, [h('span', null, String(l.qty)), ' \u00d7 ', h('span', null, l.name)]),
          h('span', { class: 'num' }, l.total),
        ])),
        h('div', { class: ['kape-line', 'kape-line--total'] }, [
          h('span', null, 'Total'),
          h('span', { class: 'num' }, String(total())),
        ]),
      ]),

      h('footer', null, [
        h('button', { class: ['kape-btn', 'kape-btn--ink'], type: 'button', onClick: () => emit('ready') }, 'Mark ready'),
        h('button', { class: 'kape-btn', type: 'button', onClick: () => emit('refund') }, 'Refund'),
      ]),
    ]);
  },
};

/** Every component, keyed the way kapehan-components.js keys them. */
export const components = {
  "button": KapeButton,
  "chip": KapeChip,
  "input": KapeInput,
  "seg": KapeSeg,
  "toast": KapeToast,
  "stamps": KapeStamps,
  "row": KapeRow,
  "stepper": KapeStepper,
  "switch": KapeSwitch,
  "check": KapeCheck,
  "select": KapeSelect,
  "tabs": KapeTabs,
  "card": KapeCard,
  "tag": KapeTag,
  "avatar": KapeAvatar,
  "dialog": KapeDialog,
  "tip": KapeTip,
  "skeleton": KapeSkeleton,
  "progress": KapeProgress,
  "pager": KapePager,
  "acc": KapeAcc,
  "table": KapeTable,
  "crumbs": KapeCrumbs,
  "upload": KapeUpload,
  "edit": KapeEdit,
  "combo": KapeCombo,
  "multi": KapeMulti,
  "range": KapeRange,
  "cmdk": KapeCmdk,
  "drawer": KapeDrawer,
};

/** Look a component up by key. Returns undefined rather than throwing, like getIcon. */
export const getComponent = (key) => components[key];
