/**
 * Kapehan for Vue.
 *
 *   import { KapeButton, KapeIcon } from 'kapehan/vue';
 *
 * Re-exports both halves. They are separate subpaths on purpose: someone who wants three
 * icons should import 'kapehan/vue/icons.js' and leave the components out of the bundle.
 *
 * GENERATED by scripts/generators/vue.mjs. Do not edit by hand.
 * MIT (c) BaryoDev. https://github.com/BaryoDev/Kapehan
 */
export * from './icons.js';
export * from './components.js';
